apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: rtalur-odf-icsp
spec:
  repositoryDigestMirrors:
  - mirrors:
    - quay.io/rhceph-dev/odf4-cephcsi-operator-bundle
    source: registry.redhat.io/odf4/cephcsi-operator-bundle
  - mirrors:
    - quay.io/rhceph-dev/odf4-cephcsi-rhel9-operator
    source: registry.redhat.io/odf4/cephcsi-rhel9-operator
  - mirrors:
    - quay.io/rhceph-dev/odf4-cephcsi-rhel9
    source: registry.redhat.io/odf4/cephcsi-rhel9
  - mirrors:
    - quay.io/rhceph-dev/odf4-mcg-core-rhel9
    source: registry.redhat.io/odf4/mcg-core-rhel9
  - mirrors:
    - quay.io/rhceph-dev/odf4-mcg-operator-bundle
    source: registry.redhat.io/odf4/mcg-operator-bundle
  - mirrors:
    - quay.io/rhceph-dev/odf4-mcg-rhel9-operator
    source: registry.redhat.io/odf4/mcg-rhel9-operator
  - mirrors:
    - quay.io/rhceph-dev/odf4-ocs-client-console-rhel9
    source: registry.redhat.io/odf4/ocs-client-console-rhel9
  - mirrors:
    - quay.io/rhceph-dev/odf4-ocs-client-operator-bundle
    source: registry.redhat.io/odf4/ocs-client-operator-bundle
  - mirrors:
    - quay.io/rhceph-dev/odf4-ocs-client-rhel9-operator
    source: registry.redhat.io/odf4/ocs-client-rhel9-operator
  - mirrors:
    - quay.io/rhceph-dev/odf4-ocs-metrics-exporter-rhel9
    source: registry.redhat.io/odf4/ocs-metrics-exporter-rhel9
  - mirrors:
    - quay.io/rhceph-dev/odf4-ocs-operator-bundle
    source: registry.redhat.io/odf4/ocs-operator-bundle
  - mirrors:
    - quay.io/rhceph-dev/odf4-ocs-rhel9-operator
    source: registry.redhat.io/odf4/ocs-rhel9-operator
  - mirrors:
    - quay.io/rhceph-dev/odf4-odf-cli-rhel9
    source: registry.redhat.io/odf4/odf-cli-rhel9
  - mirrors:
    - quay.io/rhceph-dev/odf4-odf-console-rhel9
    source: registry.redhat.io/odf4/odf-console-rhel9
  - mirrors:
    - quay.io/rhceph-dev/odf4-odf-cosi-sidecar-rhel9
    source: registry.redhat.io/odf4/odf-cosi-sidecar-rhel9
  - mirrors:
    - quay.io/rhceph-dev/odf4-odf-csi-addons-operator-bundle
    source: registry.redhat.io/odf4/odf-csi-addons-operator-bundle
  - mirrors:
    - quay.io/rhceph-dev/odf4-odf-csi-addons-rhel9-operator
    source: registry.redhat.io/odf4/odf-csi-addons-rhel9-operator
  - mirrors:
    - quay.io/rhceph-dev/odf4-odf-csi-addons-sidecar-rhel9
    source: registry.redhat.io/odf4/odf-csi-addons-sidecar-rhel9
  - mirrors:
    - quay.io/rhceph-dev/odf4-odf-multicluster-console-rhel9
    source: registry.redhat.io/odf4/odf-multicluster-console-rhel9
  - mirrors:
    - quay.io/rhceph-dev/odf4-odf-multicluster-operator-bundle
    source: registry.redhat.io/odf4/odf-multicluster-operator-bundle
  - mirrors:
    - quay.io/rhceph-dev/odf4-odf-multicluster-rhel9-operator
    source: registry.redhat.io/odf4/odf-multicluster-rhel9-operator
  - mirrors:
    - quay.io/rhceph-dev/odf4-odf-must-gather-rhel9
    source: registry.redhat.io/odf4/odf-must-gather-rhel9
  - mirrors:
    - quay.io/rhceph-dev/odf4-odf-operator-bundle
    source: registry.redhat.io/odf4/odf-operator-bundle
  - mirrors:
    - quay.io/rhceph-dev/odf4-odf-prometheus-operator-bundle
    source: registry.redhat.io/odf4/odf-prometheus-operator-bundle
  - mirrors:
    - quay.io/rhceph-dev/odf4-odf-rhel9-operator
    source: registry.redhat.io/odf4/odf-rhel9-operator
  - mirrors:
    - quay.io/rhceph-dev/odf4-odr-cluster-operator-bundle
    source: registry.redhat.io/odf4/odr-cluster-operator-bundle
  - mirrors:
    - quay.io/rhceph-dev/odf4-odr-hub-operator-bundle
    source: registry.redhat.io/odf4/odr-hub-operator-bundle
  - mirrors:
    - quay.io/rhceph-dev/odf4-odr-recipe-operator-bundle
    source: registry.redhat.io/odf4/odr-recipe-operator-bundle
  - mirrors:
    - quay.io/rhceph-dev/odf4-odr-rhel9-operator
    source: registry.redhat.io/odf4/odr-rhel9-operator
  - mirrors:
    - quay.io/rhceph-dev/odf4-rook-ceph-operator-bundle
    source: registry.redhat.io/odf4/rook-ceph-operator-bundle
  - mirrors:
    - quay.io/rhceph-dev/odf4-rook-ceph-rhel9-operator
    source: registry.redhat.io/odf4/rook-ceph-rhel9-operator
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-csi-external-attacher-rhel9
    source: registry.redhat.io/openshift4/ose-csi-external-attacher-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-csi-external-attacher-rhel9
    source: registry.redhat.io/openshift4/ose-csi-external-attacher-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-csi-external-attacher-rhel9
    source: registry.redhat.io/openshift4/ose-csi-external-attacher-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-csi-external-provisioner-rhel9
    source: registry.redhat.io/openshift4/ose-csi-external-provisioner-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-csi-external-provisioner-rhel9
    source: registry.redhat.io/openshift4/ose-csi-external-provisioner-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-csi-external-provisioner-rhel9
    source: registry.redhat.io/openshift4/ose-csi-external-provisioner-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-csi-external-resizer-rhel9
    source: registry.redhat.io/openshift4/ose-csi-external-resizer-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-csi-external-resizer-rhel9
    source: registry.redhat.io/openshift4/ose-csi-external-resizer-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-csi-external-resizer-rhel9
    source: registry.redhat.io/openshift4/ose-csi-external-resizer-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-csi-external-snapshotter-rhel9
    source: registry.redhat.io/openshift4/ose-csi-external-snapshotter-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-csi-external-snapshotter-rhel9
    source: registry.redhat.io/openshift4/ose-csi-external-snapshotter-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-csi-external-snapshotter-rhel9
    source: registry.redhat.io/openshift4/ose-csi-external-snapshotter-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-csi-node-driver-registrar-rhel9
    source: registry.redhat.io/openshift4/ose-csi-node-driver-registrar-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-csi-node-driver-registrar-rhel9
    source: registry.redhat.io/openshift4/ose-csi-node-driver-registrar-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-csi-node-driver-registrar-rhel9
    source: registry.redhat.io/openshift4/ose-csi-node-driver-registrar-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-kube-rbac-proxy-rhel9
    source: registry.redhat.io/openshift4/ose-kube-rbac-proxy-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-oauth-proxy-rhel9
    source: registry.redhat.io/openshift4/ose-oauth-proxy-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-prometheus-alertmanager-rhel9
    source: registry.redhat.io/openshift4/ose-prometheus-alertmanager-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-prometheus-config-reloader-rhel9
    source: registry.redhat.io/openshift4/ose-prometheus-config-reloader-rhel9
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-prometheus-rhel9-operator
    source: registry.redhat.io/openshift4/ose-prometheus-rhel9-operator
  - mirrors:
    - quay.io/rhceph-dev/openshift-ose-prometheus-rhel9
    source: registry.redhat.io/openshift4/ose-prometheus-rhel9
  - mirrors:
    - quay.io/rhceph-dev/rhceph-8-rhel9
    source: registry.redhat.io/rhceph/rhceph-8-rhel9
  - mirrors:
    - quay.io/rhceph-dev/rhel8-postgresql-12
    source: registry.redhat.io/rhel8/postgresql-12
  - mirrors:
    - quay.io/rhceph-dev/rhel9-postgresql-15
    source: registry.redhat.io/rhel9/postgresql-15
